### ISSUE TITLE
change size Video Recording 

### ISSUE THREAD

**Issue by J-Arji** [gorastudio/SCNRecorder#10]
Are you able to make the video a square? So the output of the recording is a movie file with a 1x1 aspect ratio?

**Comment by v-grigoriev** [comment]
No, it doesn't support such transformation so far.
You can achieve this effect by postprocessing. 
I will try to find a timeslot to make this possible in future versions.

**Comment by v-grigoriev** [comment]
@J-Arji I looked deeper into the question. It seems that a recording library isn't a good place for changing the size and aspect ratio. Of course, it can be done by adding some CIFilters to post-process frames, but it might confuse a user. On top of that, it will significantly increase the complexity of the library. I would rather suggest you change the size and position of SCNView, as other apps do for video recording, like Instagram.
