### ISSUE TITLE
Recorded audio not continuous 

### ISSUE THREAD

**Issue by bluepixeltech** [gorastudio/SCNRecorder#13]
Hi,

Thanks for the good work. I am trying to record video and audio in ARKit. I setup the audio device like you mentioned. However the audio in the recorded video is not continuous and keeps interrupting. I appreciate any help.

I am running on iOS 13.7

**Comment by v-grigoriev** [comment]
Hi @bluepixeltech!

If you are using ARKit, i.e. ARSCNView the expectation is to enable audio using `configuration.providesAudioData = true`, is that what you did?

**Comment by bluepixeltech** [comment]
Yes, I did add it. Now after removing the code snippet about setting up the AVCaptureSession the audio is being recorded correctly but it seems that the volume is very low. Do you have any idea why that might be?

________________________________

**Comment by v-grigoriev** [comment]
This is definitely unrelated to SCNRecorder. If you use AVAudioSession somewhere try to use a different configuration.

**Comment by bluepixeltech** [comment]
I have AVCaptureSession for other functionality when not in AR. Is it possible that it’s affecting the SCNRecorder?

________________________________

**Comment by v-grigoriev** [comment]
I'm not sure, I think only if you change audio device settings.

**Comment by bluepixeltech** [comment]
Thanks for the swift response.

________________________________
