### ISSUE TITLE
Record ARView in RealityKit

### ISSUE THREAD

**Issue by 0k1019** [gorastudio/SCNRecorder#16]
Hello
Thank you for the awesome project.
I wonder about the project that has a plan to record ARView.
The performance and quality in ARSCNView is really useful and awesome.
Thank you for maintaining awesome project.

**Comment by v-grigoriev** [comment]
Hello @0k1019, please take a look at Example/Source/RealityKit. I can't easily move it into the framework, but you can add this directly to your project.

**Comment by 0k1019** [comment]
@v-grigoriev Thank you for quick response. I ran Example/Source/RealityKit. It looks nice to me.
I try to add it directly to my project.
I try to find a way to move it into the framework. If I find, I will PR. 
Thank you.
