### ISSUE TITLE
.providesAudioData causes crash on iOS 14.0.1

### ISSUE THREAD

**Issue by bluepixeltech** [gorastudio/SCNRecorder#18]
Hello,

I have been using ARSceneView and SCNRecorder was perfectly capturing video with audio before upgrading to iOS 14.0. However, on iOS 14.0.1 causes a crash with:

ARKit session error: Error Domain=com.apple.arkit.error Code=102 "Required sensor failed." UserInfo={NSLocalizedFailureReason=A sensor failed to deliver the required input., NSUnderlyingError=0x282e7c570 {Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12780), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x282e66c40 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}}, NSLocalizedRecoverySuggestion=Make sure that the application has the required privacy settings., NSLocalizedDescription=Required sensor failed.}

PS: The required plist entry to access the microphone is set, the app is allowed to use the mic and everything was working just fine prior to iOS 14.

When .providesAudioData is set to false, there is no crash and the video is correctly capture (without audio). The crash happens when providesAudioData is set to true. Any idea what is happening?

Thanks

**Comment by v-grigoriev** [comment]
It can't be related to SCNRecorder and I haven't faced such issue before. Somthing should be wrong with your app configuration.
