### ISSUE TITLE
Crashes while rotating the screen on iPad

### ISSUE THREAD

**Issue by XDD2333** [gorastudio/SCNRecorder#2]
_validateGetBytes:56: failed assertion `(origin.y + size.height)(2048) must be <= height(1536).'
crashed in MetalPixelBufferProducer.swift, line 116

**Comment by v-grigoriev** [comment]
Good find. For now, rotating isn't supported. As a temporary fix, you may lock orientation while recording and recreate the whole SCNRecorder at every screen rotation.

**Comment by v-grigoriev** [comment]
Fixed in the new version.

Note. During the video recording, you would like to maintain a single orientation, otherwise, AVAssetWriter will produce a strange result.
