### ISSUE TITLE
[CoreVideo] CVPixelBuffer memory leaks

### ISSUE THREAD

**Issue by chillyjee** [gorastudio/SCNRecorder#23]
Thank you for the amazing work with SCNRecorder

I'd like to report memory leaks that occur in my case at every recording with version 2.4.0.

Here are screenshots of the memory graph and stack trace:
<img width="1676" alt="Screen Shot 2021-02-09 at 2 56 27 PM" src="https://user-images.githubusercontent.com/18469183/107322639-2fb0b980-6ae8-11eb-8aaf-7063f03c5fc7.png">
<img width="1740" alt="Screen Shot 2021-02-09 at 3 01 54 PM (2)" src="https://user-images.githubusercontent.com/18469183/107322645-350e0400-6ae8-11eb-9236-3e25003f2336.png">

The profiling was made after sceneView.cancelRecording() was called followed by sceneView de-init.

**Comment by v-grigoriev** [comment]
Fixed in #25
