### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by ramiallam** [gorastudio/SCNRecorder#27]

**Comment by v-grigoriev** [comment]
Hi @ramiallam, feel free to send PR.

**Comment by Reality-Dev** [comment]
> Hi @ramiallam, feel free to send PR.

I tried making a fork in an effort to make a PR to support Swift Package Manager, but Swift Package Manager apparently does not support multiple languages in one package, and there is at least one Objective-C file in this package. Please fix the code so it can work with SPM, it is much easier to use.

**Comment by v-grigoriev** [comment]
This is exactly why it wasn’t added initially. The objective-c file is used for a reason as the most convenient way to implement multicast delegate. Probably it can be split to a different package.

Vladislav Grigoryev

**Comment by v-grigoriev** [comment]
I moved the multicast delegate to a separate repository and added it as a dependency.
SPM support is added.
I hope I haven't missed something.
Fell free to test and open an issue if something is broken.

**Comment by Reality-Dev** [comment]
Hi @v-grigoriev ! Thank you for working on this. Unfortunately when I try to add this as a swift package it does not work. In Xcode 13.0 I go to file > Add packages and then I paste in the URL of this repository `https://github.com/gorastudio/SCNRecorder` and it tells me "The remote repository could not be accessed".
