### ISSUE TITLE
Low fps during recording on iPhone 12 Pro

### ISSUE THREAD

**Issue by juraam** [gorastudio/SCNRecorder#28]
Hello,
I use your library for recording ARSCNView and it works great. I record on the iPhone 11 and iPhone SE and it has 60 fps during recording. But when I try to record in new iPhone 12 Pro, fps drops down to 27-35 FPS. Do you know about that problem ? How can I fix it ?

**Comment by v-grigoriev** [comment]
Interesting, what version do you use?
I fixed some fps drop in 2.1.0.

Is the issue reproducible with the example app?

**Comment by juraam** [comment]
Oh, thanks man. I used 2.0.1, but when I upgraded to 2.1.0 it was okay. Thanks

**Comment by v-grigoriev** [comment]
@juraam I'd recommend to use the latest 2.6 :)

**Comment by juraam** [comment]
Okay, I will try it)
