### ISSUE TITLE
RealityKit Support

### ISSUE THREAD

**Issue by Reality-Dev** [gorastudio/SCNRecorder#29]
I know in the ReadMe it says that this package is supposed to support RealityKit:
   "To support recording RealityKit, copy ARView+MetalRecordable.swift and ARView+SelfSceneRecordable.swift files to your project. Then look at ARViewController.swift for usage."
but these files mentioned here^ seem to be missing. How do I make this work with RealityKit?

**Comment by v-grigoriev** [comment]
Oops, bad links :)
https://github.com/gorastudio/SCNRecorder/tree/master/Example/Source/Content/RealityKit

**Comment by Reality-Dev** [comment]
Thank you for responding so soon! I was able to look them up. It would help if you would update the ReadMe with the proper file links. Also, I believe the view controller example file for RealityKit is called `RealityKitViewController.swift` and not `ARViewController.swift`. Thank you for making this package! I am sure it took some time.

**Comment by v-grigoriev** [comment]
I updated the README.
