### ISSUE TITLE
Cocoapods installer doesn't find SCNRecorder

### ISSUE THREAD

**Issue by hizzlehoff** [gorastudio/SCNRecorder#3]
I can't seem to install this via cocoapods.

[!] Unable to find a specification for `SCNRecorder (~> 1.0)`

[!] Unable to find a specification for `SCNRecorder`

**Comment by v-grigoriev** [comment]
Hello! Have you updated cocoapods repo by running `pod repo update`?

**Comment by hizzlehoff** [comment]
Hi, yes.. that was it. This issue is resolved.
