### ISSUE TITLE
iOS 15 Support

### ISSUE THREAD

**Issue by Reality-Dev** [gorastudio/SCNRecorder#32]
I tested the recorder with iOS 15 beta. The recorder would run like normal but the movie files could not be saved.

**Comment by v-grigoriev** [comment]
What do you meant by “the movie files could not be saved.”? Can you share any more details? Error codes or messages?

Vladislav Grigoryev

**Comment by v-grigoriev** [comment]
I tested with iOS 15, no issue found. Unit tests passed as well.
Feel free to reopen (create another) the issue with more details.
