### ISSUE TITLE
Build error in XCode 13

### ISSUE THREAD

**Issue by juraam** [gorastudio/SCNRecorder#34]
Hi,
I tried to build my project with your library as pod and it shows error in file VideoSettings.Code.
Error text is "Enum cases with associated values cannot be marked potentially unavailable with '@available'".
`@available(iOS 13.0, *)
     case hevcWithAlpha(_ compressionProperties: HEVCCompressionProperties)`

I can build project only after deleting "@available(iOS 13.0, *)" , but this is hack.

Please can you fix this bug?

**Comment by bsdavidson** [comment]
I also ran into this issue and independently arrived at the same fix. There are other guards in the code (where `@available` annotations are still possible) to prevent using it on versions of iOS less than 13, so removing the annotation seems like the right thing to do in this case.  

I've added PR #35 to remove the available annotation.

**Comment by juraam** [comment]
@bsdavidson yes, I also saw other guards for preventing and I checked that my hack is safety.
Thank you for PR!

**Comment by DragonSpirit** [comment]
@v-grigoriev could you create a new release with this fix? If I grab dependency via pods or Carthage I have to set the "master" branch directly

**Comment by v-grigoriev** [comment]
@DragonSpirit Probably I will have some time this weekend to look at all the issues and make a release.

**Comment by v-grigoriev** [comment]
done
