### ISSUE TITLE
Video resolution seems worse than from native camera

### ISSUE THREAD

**Issue by azhong-git** [gorastudio/SCNRecorder#39]
Is this expected? anyway to get closer to native camera's video resolution?

**Comment by v-grigoriev** [comment]
Yes, this is expected. The SCNRecorder uses what you see on the screen to be recorded. So the camera feed together with AR is rendered in the size of your view multiplied by the scale. Without re-rendering, you won't get a higher resolution. But re-rendering costs a lot and you will see a huge drop in fps.
