### ISSUE TITLE
Save Video directly in the iphone library

### ISSUE THREAD

**Issue by benMOOVENCY** [gorastudio/SCNRecorder#40]
Hi, 
thanks a lot for your wonderfull job, I try to use your package and integrate it in the flutter arkit_flutter_pluggin to be able to  record directly from my flutter app.
I wondering if there is a way to save the capture directly in the gallery of the Iphone ?  

thanks again

**Comment by v-grigoriev** [comment]
Hi @benMOOVENCY, there is no way doing this from SCNRecorder.

But the result of SCNRecorder work is a URL to video file. 
So, [UISaveVideoAtPathToSavedPhotosAlbum](https://developer.apple.com/documentation/uikit/1619162-uisavevideoatpathtosavedphotosal) should perfectly work.
