### ISSUE TITLE
Choppy Video

### ISSUE THREAD

**Issue by Moazam5** [gorastudio/SCNRecorder#6]
Hi, 
This is a great framework in terms of memory consumption but the video is coming out to be choppy; not all frames are being recorded. Also I don't know how to record the audio. 
Any help will be appreciated!

**Comment by AlexanderKub** [comment]
> Hi,
> This is a great framework in terms of memory consumption but the video is coming out to be choppy; not all frames are being recorded. Also I don't know how to record the audio.
> Any help will be appreciated!

Hi, 
Maybe it can help anyone in the future, for the audio recording you need set `configuration.providesAudioData = true` in `ARWorldTrackingConfiguration`

**Comment by v-grigoriev** [comment]
> Hi,
> This is a great framework in terms of memory consumption but the video is coming out to be choppy; not all frames are being recorded. Also I don't know how to record the audio.
> Any help will be appreciated!

Could you provide more details or steps to reproduce the issue?

**Comment by v-grigoriev** [comment]
> > Hi,
> > This is a great framework in terms of memory consumption but the video is coming out to be choppy; not all frames are being recorded. Also I don't know how to record the audio.
> > Any help will be appreciated!
> 
> Hi,
> Maybe it can help anyone in the future, for the audio recording you need set `configuration.providesAudioData = true` in `ARWorldTrackingConfiguration`

Thank you @AlexanderKub for your comment! I added this information to README.
