### ISSUE TITLE
got hanging in video (while recording video with animated model)

### ISSUE THREAD

**Issue by ramakrishnaios** [gorastudio/SCNRecorder#7]
Hello this is nice framework but i found an issue in video , its getting hanging in video with animated model which is provided in attachment so please solve this issue in updated framework , it most helpful for all developers .
Thanks .

**Comment by ramakrishnaios** [comment]
i found solution now for above issue just decrease FPS (Frames per Second) 30 to 40

**Comment by v-grigoriev** [comment]
Thank you for your finding! 
I can't see the attachment to validate the issue.
But as it was already resolved I'm closing this.

PS. The new version has been released. It's even faster and more stable.

**Comment by ramakrishnaios** [comment]
give me the link for updated repository
thanks & regards,
RK.

**Comment by v-grigoriev** [comment]
@ramakrishnaios https://github.com/gorastudio/SCNRecorder
If you use cocoapods don't forget to `pod repo update`

**Comment by ramakrishnaios** [comment]
Ok bro good and thanks ,
Here I am searching dependency for arkit surface detection animations so do
you have any idea about that? Or can you refer me any tutorials or
dependencies please suggest me.
